### ISSUE TITLE
LFS data quota

### ISSUE THREAD

**Issue by ctrldrift** [Orange-OpenSource/AIVC#11]
Hi, I have been trying to clone a repo with all large files there, but got an error from git lfs 
This repository is over its data quota. 
Account responsible for LFS bandwidth should purchase more data packs to restore access.

Is there are any chances how to download all necessary files to get it running?

**Comment by pylapp** [comment]
Hi, this is organisation administrator writing.

This repository has used all the credits allocated to Git LFS, that is the reason why GitHub disabled the feature for use because the limit was exceeded.
@theoladune and @pierrick-philippe must work on another solution as soon as possible, this topic is being discussed internally.

Best regards
